### PR TITLE
Item page fixes 136

### PR DESCRIPTION
**Pull request by Kwood22**

### CODE REVIEW

**Comment by steichert** [comment]
I'm getting a lot of lag when I try drag and drop. Seems to be the same across all browsers.

**Comment by Kwood22** [comment]
I Seem to also get a lot of lag on chrome but not on firefox

**Comment by Kwood22** [comment]
To be honest I have no idea what is causing this issue, drag and drop makes use of the same functions to insert as double click. from what i can find it seems to spam the drag for much longer than necessary. The ondrop function works perfect - like 40ms

**Comment by Kwood22** [comment]
I have pushed a change that seemed to improve the performance. Can you please check if it has the same effect on your side.

**Comment by Kwood22** [comment]
I have pushed a potential fix, it has increased performance on my side, would you please verify it works on your side to.

**Comment by steichert** [comment]
I just checked now, unfortunately its still quite slow for me. I'm not sure why 🤔

**Comment by Kwood22** [comment]
Oh no.. I have no idea...  I think for some reason sortableJS is causing the issue, cause non of my functions are causing the slow down.

**Comment by SpellBreakerZA** [comment]
I also experience lag on my end. It seems that the more items you have the slower the drag and drop but as a point of reference, recipes take **much** longer...

Also sortable js seems to be sorting items alphabetically and not in the order added...

**Comment by steichert** [comment]
I've pushed some changes that I think have improved the drag & drop performance. Turns out that the drag event in Angular was causing it to slow down, so I just called (drag)="preventDefualt()" and used dragstart instead. Please check if it improved on your side as well.

**Comment by Kwood22** [comment]
Thanks bro. It seems to be much better on my side!

**Comment by vector67** [comment]
Ok cool, so it's fine now. It's still a little bit problematic on my computer, but I think we should just change the wording so that double clicking is the default mechanism and clicking and dragging isn't suggested.

**Pull request merged**
