### PR TITLE
Remove hero duplicates 156

### PR DESCRIPTION
**Pull request by steichert**
TODO:
- [x] Fix tests
- [x] Improve performance on filtering through heroes

### CODE REVIEW

**Comment by steichert** [comment]
TODO:
- [ ] Improve performance on filtering through heroes

**Comment by steichert** [comment]
@vector67 How's the performance on your side when searching through heroes?

**Comment by vector67** [comment]
@steichert It's completely fine on safari. It's a little laggy on chrome and safari, but some letters don't register, to be specific it's 's', 'v', 'w', and 'z'

**Comment by steichert** [comment]
@vector67 Those letters seem to pick up fine on my side.

**Comment by vector67** [comment]
@steichert It's to do with the fact that I use dvorak, so the code reflected the qwerty one not the dvorak. I've fixed it now so that it'll work regardless of our users' strange keyboard layouts.

**Comment by steichert** [comment]
@vector67 Ah, okay great.

**Pull request merged**
